-- MIGRAÇÃO: filtros avançados e pesquisa externa
alter table site_config add column if not exists logo_texto text default 'RA';
alter table site_config add column if not exists logo_url text;
alter table site_config add column if not exists banner_url text;
alter table site_config add column if not exists updated_at timestamp with time zone default now();
alter table site_config add column if not exists footer_text text default '© 2026 Ricardo Almeida · Corretor de Imóveis · CRECI 123456-F';
alter table site_config add column if not exists agent_url text;
alter table site_config add column if not exists mostrar_agent boolean default true;

alter table imoveis add column if not exists tipo text;
alter table imoveis add column if not exists area_m2 numeric;
alter table imoveis add column if not exists quartos integer;
alter table imoveis add column if not exists banheiros integer;
alter table imoveis add column if not exists vagas integer;
alter table imoveis add column if not exists codigo text;
alter table imoveis add column if not exists status text default 'Venda';
alter table imoveis add column if not exists finalidade text;
alter table imoveis add column if not exists bairro text;
alter table imoveis add column if not exists cidade text default 'Manaus';
alter table imoveis add column if not exists zona text;
alter table imoveis add column if not exists endereco text;
alter table imoveis add column if not exists valor_numero numeric;
alter table imoveis add column if not exists latitude numeric;
alter table imoveis add column if not exists longitude numeric;
alter table imoveis add column if not exists link_externo text;
alter table imoveis add column if not exists whatsapp_anunciante text;
update imoveis set cidade = 'Manaus' where cidade is null;
update imoveis set finalidade = status where finalidade is null and status is not null;
insert into storage.buckets (id, name, public) values ('logos','logos',true),('banners','banners',true),('imoveis','imoveis',true) on conflict (id) do nothing;
alter table site_config enable row level security;
alter table imoveis enable row level security;
alter table mensagens_contato enable row level security;
drop policy if exists "Leitura publica site_config" on site_config;
create policy "Leitura publica site_config" on site_config for select using (true);
drop policy if exists "Admin altera site_config" on site_config;
create policy "Admin altera site_config" on site_config for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists "Leitura publica imoveis ativos" on imoveis;
create policy "Leitura publica imoveis ativos" on imoveis for select using (ativo = true or auth.role() = 'authenticated');
drop policy if exists "Admin altera imoveis" on imoveis;
create policy "Admin altera imoveis" on imoveis for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists "Publico envia mensagens" on mensagens_contato;
create policy "Publico envia mensagens" on mensagens_contato for insert with check (true);
drop policy if exists "Admin le mensagens" on mensagens_contato;
create policy "Admin le mensagens" on mensagens_contato for select using (auth.role() = 'authenticated');
drop policy if exists "Leitura publica logos" on storage.objects;
create policy "Leitura publica logos" on storage.objects for select using (bucket_id in ('logos','banners','imoveis'));
drop policy if exists "Admin upload imagens" on storage.objects;
create policy "Admin upload imagens" on storage.objects for insert with check (auth.role() = 'authenticated' and bucket_id in ('logos','banners','imoveis'));
drop policy if exists "Admin atualiza imagens" on storage.objects;
create policy "Admin atualiza imagens" on storage.objects for update using (auth.role() = 'authenticated' and bucket_id in ('logos','banners','imoveis'));
drop policy if exists "Admin remove imagens" on storage.objects;
create policy "Admin remove imagens" on storage.objects for delete using (auth.role() = 'authenticated' and bucket_id in ('logos','banners','imoveis'));
