
-- CONFIGURAÇÃO COMPLETA DO SITE DO CORRETOR
-- Execute no Supabase em SQL Editor > New query > Run.

create table if not exists site_config (
  id bigint primary key default 1,
  nome_corretor text,
  creci text,
  whatsapp text,
  logo_texto text default 'RA',
  logo_url text,
  banner_url text,
  titulo_principal text,
  subtitulo_principal text,
  texto_contato text,
  updated_at timestamp with time zone default now()
);

create table if not exists imoveis (
  id bigint generated by default as identity primary key,
  titulo text,
  localizacao text,
  descricao text,
  preco text,
  detalhes text,
  imagem_url text,
  destaque text,
  ativo boolean default true,
  tipo text,
  area_m2 numeric,
  quartos integer,
  banheiros integer,
  vagas integer,
  codigo text,
  status text default 'Venda',
  created_at timestamp with time zone default now()
);

create table if not exists mensagens_contato (
  id bigint generated by default as identity primary key,
  nome text,
  whatsapp text,
  interesse text,
  mensagem text,
  created_at timestamp with time zone default now()
);

insert into site_config (
  id, nome_corretor, creci, whatsapp, logo_texto,
  titulo_principal, subtitulo_principal, texto_contato
)
values (
  1,
  'Ricardo Almeida',
  'CRECI 123456-F',
  '5592986155502',
  'RA',
  'Imóveis selecionados|para uma vida extraordinária',
  'Soluções imobiliárias personalizadas para quem busca exclusividade, segurança e os melhores investimentos.',
  'Solicite uma consultoria personalizada.'
)
on conflict (id) do nothing;

-- Buckets públicos para imagens
insert into storage.buckets (id, name, public)
values
  ('logos', 'logos', true),
  ('banners', 'banners', true),
  ('imoveis', 'imoveis', true)
on conflict (id) do nothing;

-- Row Level Security
alter table site_config enable row level security;
alter table imoveis enable row level security;
alter table mensagens_contato enable row level security;

drop policy if exists "Leitura publica site_config" on site_config;
create policy "Leitura publica site_config" on site_config for select using (true);

drop policy if exists "Admin altera site_config" on site_config;
create policy "Admin altera site_config" on site_config for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "Leitura publica imoveis ativos" on imoveis;
create policy "Leitura publica imoveis ativos" on imoveis for select using (ativo = true or auth.role() = 'authenticated');

drop policy if exists "Admin altera imoveis" on imoveis;
create policy "Admin altera imoveis" on imoveis for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "Publico envia mensagens" on mensagens_contato;
create policy "Publico envia mensagens" on mensagens_contato for insert with check (true);

drop policy if exists "Admin le mensagens" on mensagens_contato;
create policy "Admin le mensagens" on mensagens_contato for select using (auth.role() = 'authenticated');

-- Storage policies
drop policy if exists "Leitura publica logos" on storage.objects;
create policy "Leitura publica logos" on storage.objects for select using (bucket_id in ('logos','banners','imoveis'));

drop policy if exists "Admin upload imagens" on storage.objects;
create policy "Admin upload imagens" on storage.objects for insert with check (auth.role() = 'authenticated' and bucket_id in ('logos','banners','imoveis'));

drop policy if exists "Admin atualiza imagens" on storage.objects;
create policy "Admin atualiza imagens" on storage.objects for update using (auth.role() = 'authenticated' and bucket_id in ('logos','banners','imoveis'));

drop policy if exists "Admin remove imagens" on storage.objects;
create policy "Admin remove imagens" on storage.objects for delete using (auth.role() = 'authenticated' and bucket_id in ('logos','banners','imoveis'));
